### ISSUE TITLE
Abuse of test/

### ISSUE THREAD

**Issue by timholy** [bramtayl/JuliennedArrays.jl#16]
It would be better to have real tests than to co-opt it to generate the docs. Documenter has a lovely page of instructions: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/

**Comment by bramtayl** [comment]
So this was very purposeful. I chose to generate the docs in /test for a couple reasons:

1) I think doctests are really helpful in helping people understand code
2) I think all tests might as well be doctests
3) Pkg.test() should fail if doctests fail
4) doctests should contribute to coverage statistics

That said, this package certainly could use some more tests, doctests or otherwise

**Comment by timholy** [comment]
> I think doctests are really helpful in helping people understand code

True. But if I don't see a tutorial in a package, the first thing I do is turn to the `test/` directory and look for demos there.

> I think all tests might as well be doctests

LinearAlgebra runs a loop over various element types (`Float32`, `Float64`, `Complex{Float32}`, `Int`, etc.) and array types (`Array`, `SubArray`, etc.). I don't think that makes for good documentation, but it certainly makes the package robust at detecting failures.

I don't think it's crazy to run the doctests as part of the standard tests. A systematic set of tests would be good, though. It would not be hard to take the demo in #17 and juice it up with a loop or two that tests many more combinations.

**Comment by bramtayl** [comment]
Changed to use `Documenter.doctest`
