### ISSUE TITLE
Some dimensionality quirks

### ISSUE THREAD

**Issue by simonbyrne** [bramtayl/JuliennedArrays.jl#2]
Sorry it's taken me so long to look at this. Overall I really like this package, and I think it could address a lot of long-standing issues. I have a couple of suggestions.

Firstly, the size of a julienned array should match the result of `map` applied to it, i.e.
```
julia> X = [1 3 2; 5 6 4; 7 9 8]
3×3 Array{Int64,2}:
 1  3  2
 5  6  4
 7  9  8

julia> size(julienne(X,(*,:)))
(3,)

julia> size(map(identity,julienne(X,(*,:))))
(3, 1)
```

Secondly: there should also be a way to drop the sliced dimensions, perhaps by using a different symbol in the tuple, e.g.
```
julia> map(sum, julienne(X, (*,:)))
3×1 Array{Int64,2}:
  6
 15
 24

julia> map(sum, julienne(X, (*,-)))
3-element Array{Int64,1}:
  6
 15
 24
```

Finally, `combine` should work on arrays-of-arrays.

**Comment by bramtayl** [comment]
Two good reviews in the same day! 

I'm not sure if I can modify size for an julienne array, because it is an integral function to the abstractarray interface.

An interface for dropping dimensions seems like a really good idea.

I'd really like to make `combine` a much more general function which would work on arrays-of-arrays. A couple of tricky bits:

The current logic of piecing together julienned arrays makes use of a number of known facts:
1) each piece is exactly the same size
2) there is no concatenating along the same dimensions, that is:
if slices are 2 dimensional, and there slice container is 3 dimensional, they will be pieced back together into a 5 dimensional array in a way where dimensions are interwoven in a way encoded by the julienne code.

This are all features somewhat unique to a Julienne array. They also necessitate storing the julienne code in they type. Thus a mapped array from a julienneindex to julienne slice views would not be able to be flexibly pieced back together without resupplying the julienne code.

Consider an alternate reiteratedarray: a grouped array. This is actually incredibly useful in grouped/windowed table operations.

```julia
g = GroupedArray([1, 4, 3, 5, 2], [1:3, 4:5])
c = collect(g)
c == [[1, 4, 3], [5, 2]]
combine(Base.Generator(sort, g)) == [1, 3, 4, 2, 5]
```

Here the logic of combine works in a totally different way.

**Comment by simonbyrne** [comment]
One solution would be to have `julienne(X, (*,:))` to give a 3x1 array of 1x3 arrays. Then the `combine` function would "flatten" when one of the dimensions is a singleton, to give a 3x3 array.

**Comment by simonbyrne** [comment]
In that case, perhaps `collapse` would be a better name?

**Comment by bramtayl** [comment]
Yeah that seems more consistent

**Comment by bramtayl** [comment]
https://github.com/JuliaLang/julia/issues/21672

**Comment by bramtayl** [comment]
Ok, I've basically redone the interface. map will now match the size of a julienned array, and `align` is very flexible in terms of adding/dropping/moving around dimensions. I've decided it's a semantically different operation than combine. It should work on abstractarrays.
